import { useEffect, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { DndContext, closestCenter, PointerSensor, useSensor, useSensors } from '@dnd-kit/core';
import { SortableContext, arrayMove, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { IconArrowLeft, IconBook2, IconBraces, IconChevronDown, IconChevronRight, IconEdit, IconFilePlus, IconFolder, IconGripVertical, IconHistory, IconHome, IconLayoutSidebarRight, IconLock, IconPlus, IconSettings, IconTrash } from '@tabler/icons-react';
import { useWorkspace } from '../app/workspace';
import { useAuth } from '../auth';
import { bookApi } from '../entities/book/api';
import { projectApi } from '../entities/project/api';
import { scopeApi } from '../entities/scope/api';
import CompactMarkdownEditor from '../shared/ui/CompactMarkdownEditor';
import './BookerPage.css';
import './BookerCover.css';
import './BookerBlocks.css';
import './BookerBlockEditing.css';
import './BookerDataBlocks.css';
import './BookerPageActions.css';
import './BookerDnd.css';
import './BookerStructureDnd.css';
import './BookerSticky.css';
import './BookerExcalidraw.css';
import './BookerHistory.css';
import './BookerStructuredEditors.css';

const BLOCK_TYPES = [['markdown', 'Текст'], ['callout', 'Врезка'], ['code', 'Код'], ['checklist', 'Чеклист'], ['table', 'Таблица'], ['svg', 'SVG'], ['excalidraw', 'Схема'], ['embed', 'Встраивание'], ['divider', 'Разделитель']];
let ExcalidrawComponent = null; let exportExcalidrawToSvg = null;
async function loadExcalidraw() { if (ExcalidrawComponent && exportExcalidrawToSvg) return { Excalidraw: ExcalidrawComponent, exportToSvg: exportExcalidrawToSvg }; const [module] = await Promise.all([import('@excalidraw/excalidraw'), import('@excalidraw/excalidraw/index.css')]); ExcalidrawComponent = module.Excalidraw; exportExcalidrawToSvg = module.exportToSvg; return { Excalidraw: ExcalidrawComponent, exportToSvg: exportExcalidrawToSvg }; }

export function BookerPage() {
    const { activeScope } = useWorkspace(); const queryClient = useQueryClient();
    const navigate = useNavigate(); const { bookId: routeBookId, pageId: routePageId, blockId, versionId } = useParams();
    const { data: scopes = [] } = useQuery({ queryKey: ['scopes'], queryFn: scopeApi.list });
    const { data: projects = [] } = useQuery({ queryKey: ['projects', activeScope?.id], queryFn: () => projectApi.list(activeScope.id), enabled: Boolean(activeScope) });
    const selectScope = (scopeId) => { localStorage.setItem('zuratax-active-scope', scopeId); window.location.reload(); };
    const bookId = routeBookId ?? null; const pageId = routePageId ?? null; const [form, setForm] = useState(null);
    const selectBook = (nextBookId) => { if (!nextBookId) { navigate('/books'); return; } const remembered = localStorage.getItem(`booker:last:${activeScope.id}:${nextBookId}`); navigate(remembered && remembered !== 'cover' ? `/books/${nextBookId}/pages/${remembered}` : `/books/${nextBookId}`); };
    const selectPage = (nextPageId) => { if (!bookId) return; localStorage.setItem(`booker:last:${activeScope.id}:${bookId}`, nextPageId ?? 'cover'); navigate(nextPageId ? `/books/${bookId}/pages/${nextPageId}` : `/books/${bookId}`); };
    const { data: spaces = [] } = useQuery({ queryKey: ['book-spaces', activeScope?.id], queryFn: () => bookApi.spaces(activeScope.id), enabled: Boolean(activeScope) });
    const { data: books = [] } = useQuery({ queryKey: ['books', activeScope?.id], queryFn: () => bookApi.books(activeScope.id), enabled: Boolean(activeScope) });
    const activeBook = books.find((book) => book.id === bookId) ?? null;
    const { data: pages = [] } = useQuery({ queryKey: ['book-pages', activeScope?.id, bookId], queryFn: () => bookApi.pages(activeScope.id, bookId), enabled: Boolean(activeScope && bookId) });
    const activePageId = pageId;
    const { data: page, isLoading } = useQuery({ queryKey: ['book-page', activeScope?.id, bookId, activePageId], queryFn: () => bookApi.page(activeScope.id, bookId, activePageId), enabled: Boolean(activeScope && bookId && activePageId), refetchInterval: 15000 });
    const loadedPageId = page?.id; const loadedGroupCount = page?.groups?.length;
    const refreshBooks = () => queryClient.invalidateQueries({ queryKey: ['books', activeScope.id] });
    const refreshPages = () => queryClient.invalidateQueries({ queryKey: ['book-pages', activeScope.id, bookId] });
    const refreshPage = () => queryClient.invalidateQueries({ queryKey: ['book-page', activeScope.id, bookId, activePageId] });
    useEffect(() => { if (!blockId || !loadedPageId) return; const frame = window.requestAnimationFrame(() => document.getElementById(`block-${blockId}`)?.scrollIntoView({ behavior: 'smooth', block: 'center' })); return () => window.cancelAnimationFrame(frame); }, [blockId, versionId, loadedPageId, loadedGroupCount]);
    return <main className="booker-page">
        <BookerNavigation spaces={spaces} books={books} activeBook={activeBook} pages={pages} pageId={activePageId} setBookId={selectBook} setPageId={selectPage} setForm={setForm} scopeId={activeScope?.id} refreshBooks={refreshBooks}/>
        <section className="booker-content">{!bookId && <BookerWelcome/>}{activeBook && !activePageId && <BookCover scopeId={activeScope.id} book={activeBook} spaces={spaces} scopes={scopes} projects={projects} selectScope={selectScope} refresh={refreshBooks}/>} {isLoading && <div className="booker-empty">Загружаю страницу…</div>}{page && <BookPage scopeId={activeScope.id} bookId={bookId} page={page} refresh={refreshPage}/>}</section>
        <PageStructure scopeId={activeScope?.id} bookId={bookId} pageId={activePageId} page={page} editingBy={page?.editing_by} groups={page?.groups ?? []} refresh={refreshPage}/>
        {form && <CreateBookerEntity form={form} setForm={setForm} scopeId={activeScope.id} bookId={bookId} spaces={spaces} scopes={scopes} pages={pages} onCreated={(entity, targetScopeId) => { if (form.type === 'space') queryClient.invalidateQueries({ queryKey: ['book-spaces', activeScope.id] }); if (form.type === 'book') { if (targetScopeId !== activeScope.id) selectScope(targetScopeId); else { refreshBooks(); selectBook(entity.id); } } if (form.type === 'page') { refreshPages(); selectPage(entity.id); } setForm(null); }}/>} 
    </main>;
}

function BookerNavigation({ spaces, books, activeBook, pages, pageId, setBookId, setPageId, setForm, scopeId, refreshBooks }) {
    const updateDepth = useMutation({ mutationFn: (depth) => bookApi.updateBook(scopeId, activeBook.id, { version_depth: depth }), onSuccess: refreshBooks });
    if (activeBook) return <aside className="booker-nav"><header><button title="К списку книг" onClick={() => { setBookId(null); setPageId(null); }}><IconArrowLeft size={16}/></button><strong title={activeBook.title}>{activeBook.title}</strong><button title="Новая страница" onClick={() => setForm({ type: 'page' })}><IconFilePlus size={16}/></button></header><nav className="booker-page-tree"><button className={pageId === null ? 'active book-root' : 'book-root'} onClick={() => setPageId(null)}><IconHome size={13}/><span>{activeBook.title}</span></button>{treePages(pages).map((item) => <button key={item.id} className={item.id === pageId ? 'active' : ''} style={{ paddingLeft: 9 + item.depth * 14 }} onClick={() => setPageId(item.id)}><IconChevronRight size={13}/><span>{item.title}</span></button>)}</nav><label className="booker-depth"><IconSettings size={14}/><span>Глубина истории</span><input type="number" min="1" max="100" defaultValue={activeBook.version_depth ?? 25} onBlur={(event) => updateDepth.mutate(Number(event.target.value))}/></label></aside>;
    return <aside className="booker-nav"><header><strong><IconBook2 size={18}/>Booker</strong><button title="Новый раздел" onClick={() => setForm({ type: 'space' })}><IconPlus size={16}/></button></header>{spaces.map((space) => <section key={space.id}><h3><IconFolder size={14}/>{space.title}</h3>{books.filter((book) => book.space_id === space.id).map((book) => <BookRow key={book.id} book={book} onClick={() => setBookId(book.id)}/>)}</section>)}<section><h3>Без раздела</h3>{books.filter((book) => !book.space_id).map((book) => <BookRow key={book.id} book={book} onClick={() => setBookId(book.id)}/>)}</section><button className="booker-add" onClick={() => setForm({ type: 'book', space_id: spaces[0]?.id ?? '' })}><IconPlus size={15}/>Новая книга</button></aside>;
}

function BookRow({ book, onClick }) { return <button onClick={onClick}><span>{book.title}</span><small>{book.pages_count}</small></button>; }

function BookCover({ scopeId, book, spaces, scopes, projects, selectScope, refresh }) {
    const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(() => bookDraft(book));
    const firstEditRender = useRef(true);
    const save = useMutation({ mutationFn: (nextDraft = draft) => bookApi.updateBook(scopeId, book.id, { ...nextDraft, space_id: nextDraft.scope_id === scopeId ? nextDraft.space_id || null : null, version_depth: Number(nextDraft.version_depth) }), onSuccess: (_, nextDraft) => { const saved = nextDraft ?? draft; if (saved.scope_id !== scopeId) selectScope(saved.scope_id); else refresh(); } });
    // The mutation object is intentionally excluded: TanStack recreates it and would restart the debounce timer.
    // oxlint-disable-next-line react-hooks/exhaustive-deps
    useEffect(() => { if (!editing) { firstEditRender.current = true; return; } if (firstEditRender.current) { firstEditRender.current = false; return; } const timer = window.setTimeout(() => save.mutate(draft), 800); return () => window.clearTimeout(timer); }, [draft, editing]);
    const coverSource = draft.cover_svg_text ? `data:image/svg+xml;charset=utf-8,${encodeURIComponent(draft.cover_svg_text)}` : draft.cover_svg_url || null;
    if (editing) return <article className="book-cover book-cover--editing"><header><div><small>Настройки книги · {save.isPending ? 'сохраняю…' : save.isSuccess ? 'сохранено' : 'автосохранение'}</small><h1>{book.title}</h1></div><div><button className="primary" onClick={() => { save.mutate(draft); setEditing(false); }}>Выйти из режима редактирования</button></div></header><div className="book-cover-form"><label>Название<input value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })}/></label><label>Скоуп<select value={draft.scope_id} onChange={(event) => setDraft({ ...draft, scope_id: event.target.value, space_id: '', project_id: '' })}>{scopes.map((scope) => <option key={scope.id} value={scope.id}>{scope.name}</option>)}</select></label><label>Проект<select disabled={draft.scope_id !== scopeId} value={draft.project_id} onChange={(event) => setDraft({ ...draft, project_id: event.target.value })}><option value="">Без проекта</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.key} · {project.title}</option>)}</select></label><label>Раздел Booker<select disabled={draft.scope_id !== scopeId} value={draft.space_id} onChange={(event) => setDraft({ ...draft, space_id: event.target.value })}><option value="">Без раздела</option>{spaces.map((space) => <option key={space.id} value={space.id}>{space.title}</option>)}</select></label><label>Видимость<select value={draft.visibility} onChange={(event) => setDraft({ ...draft, visibility: event.target.value })}><option value="private">Приватная</option><option value="scope">В скоупе</option><option value="public">Публичная</option></select></label><label>Структура<select value={draft.structure_mode} onChange={(event) => setDraft({ ...draft, structure_mode: event.target.value })}><option value="tree">Дерево</option><option value="flat">Плоская</option></select></label><label>Глубина версий<input type="number" min="1" max="100" value={draft.version_depth} onChange={(event) => setDraft({ ...draft, version_depth: event.target.value })}/></label><label>Цвет обложки<input value={draft.cover_color} placeholder="#eaf2ff" onChange={(event) => setDraft({ ...draft, cover_color: event.target.value })}/></label><label className="wide">Описание<textarea rows="5" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })}/></label><label className="wide">URL обложки SVG<input value={draft.cover_svg_url} onChange={(event) => setDraft({ ...draft, cover_svg_url: event.target.value, cover_svg_text: event.target.value ? '' : draft.cover_svg_text })}/></label><label className="wide">Или SVG-код<textarea rows="7" value={draft.cover_svg_text} onChange={(event) => setDraft({ ...draft, cover_svg_text: event.target.value, cover_svg_url: event.target.value ? '' : draft.cover_svg_url })}/></label></div>{save.error && <p className="booker-error">{save.error.message}</p>}</article>;
    return <article className="book-cover"><div className="book-cover-visual" style={{ background: book.cover_color || '#eaf2ff' }}>{coverSource ? <img src={coverSource} alt=""/> : <IconBook2 size={54}/>}</div><div className="book-cover-copy"><small>Книга · {book.visibility === 'public' ? 'публичная' : book.visibility === 'scope' ? 'в скоупе' : 'приватная'}</small><h1>{book.title}</h1><p>{book.description || 'Добавьте описание — что находится в книге и для кого она собрана.'}</p><dl><div><dt>Страниц</dt><dd>{book.pages_count ?? 0}</dd></div><div><dt>Структура</dt><dd>{book.structure_mode === 'flat' ? 'Плоская' : 'Дерево'}</dd></div><div><dt>История</dt><dd>{book.version_depth ?? 25}</dd></div></dl><button onClick={() => { setDraft(bookDraft(book)); setEditing(true); }}><IconEdit size={14}/>Редактировать свойства</button></div></article>;
}

function BookPage({ scopeId, bookId, page, refresh }) {
    const user = useAuth((state) => state.user); const queryClient = useQueryClient(); const key = ['book-page', scopeId, bookId, page.id]; const editing = page.editing_by === user?.id; const canEdit = page.created_by === user?.id;
    const [editingGroup, setEditingGroup] = useState(null);
    const acquire = useMutation({ mutationFn: (group) => bookApi.acquireEditing(scopeId, bookId, page.id).then((next) => ({ next, group })), onSuccess: ({ next, group }) => { queryClient.setQueryData(key, next); if (group) setEditingGroup(next.groups?.find((item) => item.id === group.id) ?? group); } });
    const release = useMutation({ mutationFn: () => bookApi.releaseEditing(scopeId, bookId, page.id), onSuccess: (next) => { queryClient.setQueryData(key, next); setEditingGroup(null); } });
    const cancelEditing = useMutation({ mutationFn: () => bookApi.cancelEditing(scopeId, bookId, page.id), onSuccess: (next) => { queryClient.setQueryData(key, next); setEditingGroup(null); refresh(); } });
    const saveTitle = useMutation({ mutationFn: (title) => bookApi.updatePage(scopeId, bookId, page.id, { title }), onSuccess: (updated) => queryClient.setQueryData(key, updated) });
    const addBlock = useMutation({ mutationFn: (type) => bookApi.createBlock(scopeId, bookId, page.id, { type, sort_order: page.groups?.length ?? 0, content: type === 'divider' ? null : '' }), onSuccess: refresh });
    const reorder = useMutation({ mutationFn: (groups) => bookApi.reorderBlocks(scopeId, bookId, page.id, groups.map((group, index) => ({ id: group.id, sort_order: index + 1 }))), onSuccess: refresh });
    return <article className="book-page-editor"><header>{editing ? <input value={page.title} onChange={(event) => queryClient.setQueryData(key, { ...page, title: event.target.value })} onBlur={(event) => saveTitle.mutate(event.target.value)}/> : <h1>{page.title}</h1>}<div className="booker-edit-actions"><small>{page.versions_count ?? 0} снимков</small>{editing ? <><button className="booker-cancel-edit" disabled={cancelEditing.isPending} onClick={() => cancelEditing.mutate()}>Отменить изменения</button><button onClick={() => release.mutate()}><IconLock size={14}/>Закрыть редактор</button></> : canEdit && <button disabled={Boolean(page.editing_by) || acquire.isPending} onClick={() => acquire.mutate(null)}><IconEdit size={14}/>Редактировать</button>}</div></header>{!editing && page.editing_by && <div className="booker-lock"><IconLock size={16}/>Страницу редактирует <strong>{page.editor?.name ?? page.editor?.username ?? 'другой пользователь'}</strong>. Пока доступен просмотр и навигация.</div>}{(acquire.error || cancelEditing.error || reorder.error) && <p className="booker-error">{acquire.error?.message ?? cancelEditing.error?.message ?? reorder.error?.message}</p>}<BlocksCanvas groups={page.groups ?? []} editing={editing} canEdit={canEdit && !page.editing_by} onEdit={(group) => editing ? setEditingGroup(group) : acquire.mutate(group)} onReorder={(groups) => reorder.mutate(groups)}/>{editing && <div className="booker-add-block"><span>Добавить блок</span>{BLOCK_TYPES.map(([type, label]) => <button key={type} disabled={addBlock.isPending} onClick={() => addBlock.mutate(type)}>{label}</button>)}</div>}{editingGroup && <BlockEditorModal key={editingGroup.master_block_id} scopeId={scopeId} bookId={bookId} pageId={page.id} group={editingGroup} refresh={refresh} onClose={() => setEditingGroup(null)}/>}</article>;
}

function BlocksCanvas({ groups, editing, canEdit, onEdit, onReorder }) {
    const [items, setItems] = useState(groups);
    const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }));
    // Server refreshes replace the immutable group list after saves and rollbacks.
    // oxlint-disable-next-line react-hooks/set-state-in-effect
    useEffect(() => setItems(groups), [groups]);
    const dragEnd = ({ active, over }) => { if (!over || active.id === over.id) return; const oldIndex = items.findIndex((item) => item.id === active.id); const newIndex = items.findIndex((item) => item.id === over.id); const reordered = arrayMove(items, oldIndex, newIndex); setItems(reordered); onReorder(reordered); };
    const content = <SortableContext items={items.map((item) => item.id)} strategy={verticalListSortingStrategy}>{items.map((group) => <SortableBookBlock key={group.id} group={group} editing={editing} canEdit={canEdit} onEdit={() => onEdit(group)}/>)}</SortableContext>;
    return <div className={`book-blocks ${editing ? 'is-editing' : ''}`}>{editing ? <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={dragEnd}>{content}</DndContext> : content}</div>;
}

function SortableBookBlock(props) {
    const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: props.group.id, disabled: !props.editing });
    return <div ref={setNodeRef} style={{ transform: CSS.Transform.toString(transform), transition, opacity: isDragging ? .45 : 1 }}><BookBlock {...props} dragAttributes={attributes} dragListeners={listeners}/></div>;
}

function BookBlock({ group, editing, canEdit, onEdit, dragAttributes, dragListeners }) {
    const block = group.master_block ?? {};
    return <section id={`block-${group.id}`} className={`book-block book-block--${group.type}`} onDoubleClick={editing ? onEdit : undefined}>{editing && <button className="book-block-grip" title="Перетащить блок" onDoubleClick={(event) => event.stopPropagation()} {...dragAttributes} {...dragListeners}><IconGripVertical size={15}/></button>}<button className="book-block-edit" title="Редактировать блок" onClick={(event) => { event.stopPropagation(); onEdit(); }} disabled={!editing && !canEdit}><IconEdit size={15}/></button><label>{BLOCK_TYPES.find(([type]) => type === group.type)?.[1] ?? group.type}<small>v{block.version_number ?? 1}</small></label>{group.type === 'divider' ? <hr className="book-block-divider"/> : <BlockPreview type={group.type} block={block}/>}</section>;
}

function BlockEditorModal(props) { return props.group.type === 'excalidraw' ? <ExcalidrawBlockEditorModal {...props}/> : <DataBlockEditorModal {...props}/>; }

function ExcalidrawBlockEditorModal({ scopeId, bookId, pageId, group, refresh, onClose }) {
    const [initialPayload] = useState(() => group.master_block?.payload ?? {}); const timer = useRef(null);
    const [editor, setEditor] = useState(null); const [exporter, setExporter] = useState(null); const [api, setApi] = useState(null); const [loadError, setLoadError] = useState(null);
    const save = useMutation({ mutationFn: (payload) => bookApi.createVersion(scopeId, bookId, pageId, group.id, { payload, search_text: 'Excalidraw drawing', status: 'draft' }), onSuccess: refresh });
    useEffect(() => { let alive = true; loadExcalidraw().then(({ Excalidraw, exportToSvg }) => { if (!alive) return; setEditor(() => Excalidraw); setExporter(() => exportToSvg); }).catch((error) => { if (alive) setLoadError(error); }); return () => { alive = false; if (timer.current) window.clearTimeout(timer.current); }; }, []);
    const buildPayload = async () => { if (!api || !exporter) return initialPayload; const elements = api.getSceneElements(); const appState = api.getAppState(); const files = api.getFiles(); const svg = await exporter({ elements, appState, files }); return { scene: { elements, appState, files }, svg: svg.outerHTML }; };
    const saveCurrent = async (closeAfter = false) => { if (timer.current) window.clearTimeout(timer.current); const payload = await buildPayload(); save.mutate(payload, { onSuccess: () => { refresh(); if (closeAfter) onClose(); } }); };
    const scheduleSave = () => { if (timer.current) window.clearTimeout(timer.current); timer.current = window.setTimeout(() => void saveCurrent(false), 1200); };
    const cancel = () => { if (timer.current) window.clearTimeout(timer.current); save.mutate(initialPayload, { onSuccess: () => { refresh(); onClose(); } }); };
    const Excalidraw = editor;
    return <div className="excalidraw-editor-backdrop"><section className="excalidraw-editor-modal"><header><div><strong>Excalidraw</strong><small>{save.isPending ? 'Сохраняю сцену…' : save.isSuccess ? 'Сохранено' : 'Автосохранение'}</small></div><span>Версия {group.master_block?.version_number ?? 1}</span></header><div className="excalidraw-editor-canvas">{loadError ? <div className="excalidraw-editor-loading">Не удалось загрузить Excalidraw: {loadError.message}</div> : !Excalidraw ? <div className="excalidraw-editor-loading">Загружаю Excalidraw…</div> : <Excalidraw excalidrawAPI={setApi} initialData={initialPayload.scene ?? null} onChange={scheduleSave} UIOptions={{ canvasActions: { export: false, loadScene: false } }}/>}</div><footer><button className="cancel" onClick={cancel}>Отменить изменения</button><button className="primary" onClick={() => void saveCurrent(true)}>Закрыть редактор</button></footer></section></div>;
}

function DataBlockEditorModal({ scopeId, bookId, pageId, group, refresh, onClose }) {
    const isMarkdown = group.type === 'markdown';
    const original = useRef(isMarkdown ? group.master_block?.content ?? '' : { ...(group.master_block?.payload ?? defaultPayload(group.type)) });
    const [value, setValue] = useState(original.current);
    const firstRender = useRef(true);
    const payloadFor = (next) => isMarkdown ? { content: next, search_text: next, status: 'draft' } : { payload: next, search_text: JSON.stringify(next), status: 'draft' };
    const save = useMutation({ mutationFn: (next) => bookApi.createVersion(scopeId, bookId, pageId, group.id, payloadFor(next)), onSuccess: refresh });
    // oxlint-disable-next-line react-hooks/exhaustive-deps
    useEffect(() => { if (firstRender.current) { firstRender.current = false; return; } const timer = window.setTimeout(() => save.mutate(value), 700); return () => window.clearTimeout(timer); }, [value]);
    const cancel = () => save.mutate(original.current, { onSuccess: () => { refresh(); onClose(); } });
    const close = () => save.mutate(value, { onSuccess: () => { refresh(); onClose(); } });
    const setField = (field, next) => setValue((current) => ({ ...current, [field]: next }));
    return <div className="block-editor-backdrop" onMouseDown={close}><section className="block-editor-modal" onMouseDown={(event) => event.stopPropagation()}><header><div><small>{BLOCK_TYPES.find(([type]) => type === group.type)?.[1] ?? group.type}</small><h2>Редактирование блока</h2></div><span>{save.isPending ? 'Сохраняю…' : save.isSuccess ? 'Сохранено' : 'Автосохранение'}</span></header><div className="block-editor-content">{isMarkdown ? <CompactMarkdownEditor value={value} onChange={setValue} placeholder="Текст страницы в Markdown…" toolbarInitiallyOpen variant="full"/> : group.type === 'svg' ? <SvgFields value={value} setValue={setValue} setField={setField}/> : ['callout', 'checklist', 'code', 'embed'].includes(group.type) ? <StructuredBlockFields type={group.type} value={value} setField={setField}/> : <JsonFields value={value} setValue={setValue}/>}</div><footer><button className="cancel" onClick={cancel}>Отменить изменения</button><button className="primary" onClick={close}>Закрыть редактор</button></footer></section></div>;
}

function StructuredBlockFields({ type, value, setField }) {
    if (type === 'code') return <div className="booker-data-fields"><div className="booker-field-row"><label>Подпись<input value={value.caption ?? ''} onChange={(event) => setField('caption', event.target.value)}/></label><label>Язык<input value={value.language ?? ''} placeholder="javascript, php, sql…" onChange={(event) => setField('language', event.target.value)}/></label></div><label className="booker-field-grow">Код<textarea className="booker-code-field" value={value.code ?? ''} spellCheck="false" onChange={(event) => setField('code', event.target.value)}/></label></div>;
    if (type === 'callout') return <div className="booker-data-fields"><div className="booker-field-row"><label>Заголовок<input value={value.title ?? ''} onChange={(event) => setField('title', event.target.value)}/></label><label>Тон<select value={value.tone ?? 'info'} onChange={(event) => setField('tone', event.target.value)}><option value="info">Информация</option><option value="success">Успех</option><option value="warning">Предупреждение</option><option value="danger">Опасность</option></select></label></div><label className="booker-field-grow">Текст<textarea value={value.text ?? ''} onChange={(event) => setField('text', event.target.value)}/></label></div>;
    if (type === 'embed') return <div className="booker-data-fields"><label>Заголовок<input value={value.title ?? ''} onChange={(event) => setField('title', event.target.value)}/></label><label>Ссылка<input type="url" value={value.url ?? ''} placeholder="https://…" onChange={(event) => setField('url', event.target.value)}/></label><label className="booker-field-grow">Описание<textarea value={value.description ?? ''} onChange={(event) => setField('description', event.target.value)}/></label></div>;
    return <ChecklistFields items={Array.isArray(value.items) ? value.items : []} onChange={(items) => setField('items', items)}/>;
}

function ChecklistFields({ items, onChange }) {
    const update = (index, field, next) => onChange(items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: next } : item));
    return <div className="booker-checklist-editor"><header><strong>Пункты чеклиста</strong><button type="button" onClick={() => onChange([...items, { text: '', checked: false }])}><IconPlus size={14}/>Добавить пункт</button></header><div>{items.map((item, index) => <div className="booker-checklist-editor-row" key={index}><input type="checkbox" checked={Boolean(item.checked)} onChange={(event) => update(index, 'checked', event.target.checked)}/><input autoFocus={items.length === 1 && !item.text} value={item.text ?? ''} placeholder="Что нужно сделать?" onChange={(event) => update(index, 'text', event.target.value)}/><button type="button" title="Удалить пункт" onClick={() => onChange(items.filter((_, itemIndex) => itemIndex !== index))}><IconTrash size={14}/></button></div>)}</div>{items.length === 0 && <p>Пока пусто. Добавьте первый пункт.</p>}</div>;
}

function SvgFields({ value, setValue, setField }) { return <div className="svg-block-editor"><div className="svg-source-tabs">{['url', 'inline', 'file'].map((source) => <button key={source} className={value.source === source ? 'active' : ''} onClick={() => setField('source', source)}>{source === 'url' ? 'URL' : source === 'inline' ? 'Inline' : 'Файл'}</button>)}</div>{value.source === 'url' && <label>SVG URL<input value={value.url ?? ''} placeholder="https://…/diagram.svg" onChange={(event) => setField('url', event.target.value)}/></label>}{value.source === 'inline' && <label>SVG-код<textarea rows="12" value={value.svg_text ?? ''} placeholder={'<svg viewBox="0 0 100 100">…</svg>'} onChange={(event) => setField('svg_text', event.target.value)}/></label>}{value.source === 'file' && <label>SVG-файл<input type="file" accept=".svg,image/svg+xml" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; setValue({ ...value, source: 'file', svg_text: await file.text(), file_name: file.name }); }}/>{value.file_name && <small>Загружен: {value.file_name}</small>}</label>}<label>Подпись<input value={value.caption ?? ''} onChange={(event) => setField('caption', event.target.value)}/></label><div className="svg-size-fields"><label>Макс. ширина<input value={value.max_width ?? ''} placeholder="100%, 720px, 48rem" onChange={(event) => setField('max_width', event.target.value)}/></label><label>Макс. высота<input value={value.max_height ?? ''} placeholder="620px, 70vh, auto" onChange={(event) => setField('max_height', event.target.value)}/></label></div></div>; }
function JsonFields({ value, setValue }) { const [raw, setRaw] = useState(() => JSON.stringify(value, null, 2)); const [invalid, setInvalid] = useState(false); return <label className="json-block-editor">Payload JSON<textarea className="block-editor-main" value={raw} onChange={(event) => { const next = event.target.value; setRaw(next); try { setValue(JSON.parse(next)); setInvalid(false); } catch { setInvalid(true); } }}/>{invalid && <small>JSON пока невалиден — автосохранение ждёт исправления.</small>}</label>; }

function BlockPreview({ type, block }) { const payload = block.payload ?? {}; if (type === 'code') return <div>{payload.caption && <small>{payload.caption} · {payload.language || 'text'}</small>}<pre><code>{payload.code || block.content || 'Пустой блок кода'}</code></pre></div>; if (type === 'callout') return <div className="book-block-content"><strong>{payload.title}</strong>{payload.title && '\n'}{payload.text || block.content || 'Пустая врезка'}</div>; if (type === 'embed') return <div className="book-block-content"><strong>{payload.title || 'Ссылка'}</strong>{'\n'}{payload.description}{payload.url && <><br/><a href={payload.url} target="_blank" rel="noreferrer">{payload.url}</a></>}</div>; if (type === 'checklist') { const items = Array.isArray(payload.items) ? payload.items : (block.content || '').split('\n').filter(Boolean).map((text) => ({ text, checked: false })); return <div className="book-checklist">{items.map((item, index) => <label key={index}><input type="checkbox" checked={Boolean(item.checked)} disabled/>{item.text}</label>)}</div>; } if (type === 'table') return <div className="book-table-scroll"><table style={{ minWidth: payload.min_width || '720px' }}><thead><tr>{(payload.columns ?? []).map((column, index) => <th key={index}>{column}</th>)}</tr></thead><tbody>{(payload.rows ?? []).map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; if (type === 'svg') { const src = payload.url || (payload.svg_text ? svgTextToDataUrl(payload.svg_text) : ''); return <figure className="book-svg-preview" style={{ '--svg-max-width': payload.max_width || '100%', '--svg-max-height': payload.max_height || '620px' }}>{src ? <img src={src} alt={payload.caption || 'SVG asset'} loading="lazy"/> : <div className="book-block-placeholder">Источник SVG не задан</div>}{payload.caption && <figcaption>{payload.caption}</figcaption>}</figure>; } if (type === 'excalidraw') return payload.svg ? <div className="book-excalidraw-preview"><img src={svgTextToDataUrl(payload.svg)} alt="Схема Excalidraw" loading="lazy"/></div> : <div className="book-block-placeholder"><IconBraces size={20}/>Пустая сцена — откройте редактор двойным кликом</div>; return <div className="book-block-content">{block.content || payload.label || 'Пустой блок'}</div>; }
function PageStructure({ scopeId, bookId, pageId, page, editingBy, groups, refresh }) {
    const user = useAuth((state) => state.user); const editing = editingBy === user?.id; const [items, setItems] = useState(groups); const queryClient = useQueryClient();
    const navigate = useNavigate(); const { pageVersionId } = useParams(); const [versionsOpen, setVersionsOpen] = useState(Boolean(pageVersionId)); const [selectedVersionId, setSelectedVersionId] = useState(pageVersionId ?? null);
    const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }));
    // oxlint-disable-next-line react-hooks/set-state-in-effect
    useEffect(() => setItems(groups), [groups]);
    // oxlint-disable-next-line react-hooks/set-state-in-effect
    useEffect(() => { setSelectedVersionId(pageVersionId ?? null); if (pageVersionId) setVersionsOpen(true); }, [pageVersionId]);
    const reorder = useMutation({ mutationFn: (next) => bookApi.reorderBlocks(scopeId, bookId, pageId, next.map((group, index) => ({ id: group.id, sort_order: index + 1 }))), onSuccess: refresh, onError: () => setItems(groups) });
    const { data: versions = [], isLoading: versionsLoading } = useQuery({ queryKey: ['book-page-versions', scopeId, bookId, pageId], queryFn: () => bookApi.pageVersions(scopeId, bookId, pageId), enabled: Boolean(versionsOpen && pageId) });
    const { data: selectedVersion } = useQuery({ queryKey: ['book-page-version', scopeId, bookId, pageId, selectedVersionId], queryFn: () => bookApi.pageVersion(scopeId, bookId, pageId, selectedVersionId), enabled: Boolean(selectedVersionId) });
    const restore = useMutation({ mutationFn: (versionId) => bookApi.restorePageVersion(scopeId, bookId, pageId, versionId), onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ['book-page', scopeId, bookId, pageId] }), queryClient.invalidateQueries({ queryKey: ['book-pages', scopeId, bookId] }), queryClient.invalidateQueries({ queryKey: ['book-page-versions', scopeId, bookId, pageId] })]); navigate(`/books/${bookId}/pages/${pageId}`); } });
    const dragEnd = ({ active, over }) => { if (!over || active.id === over.id) return; const oldIndex = items.findIndex((item) => item.id === active.id); const newIndex = items.findIndex((item) => item.id === over.id); const next = arrayMove(items, oldIndex, newIndex); setItems(next); reorder.mutate(next); };
    const list = <SortableContext items={items.map((item) => item.id)} strategy={verticalListSortingStrategy}>{items.map((group, index) => <SortableStructureItem key={group.id} group={group} index={index} bookId={bookId} pageId={pageId} editing={editing}/>)}</SortableContext>;
    return <aside className={`booker-structure ${editing ? 'is-editing' : ''}`}><header><IconLayoutSidebarRight size={16}/><strong>Структура</strong>{reorder.isPending && <small>сохраняю…</small>}</header><div className="booker-structure-list">{items.length === 0 ? <p>На странице пока нет блоков.</p> : editing ? <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={dragEnd}>{list}</DndContext> : list}</div>{pageId && <div className="booker-history"><button className="booker-history-trigger" onClick={() => setVersionsOpen((open) => !open)}><IconHistory size={14}/><span>История версий</span><small>{page?.versions_count ?? versions.length}</small><IconChevronDown className={versionsOpen ? 'open' : ''} size={13}/></button>{versionsOpen && <div className="booker-version-list">{versionsLoading ? <p>Загружаю…</p> : versions.length === 0 ? <p>Снимков пока нет.</p> : versions.map((version) => <button key={version.id} onClick={() => navigate(`/books/${bookId}/pages/${pageId}/versions/${version.id}`)}><strong>Snapshot {version.version_number}</strong><span>{version.creator?.name ?? version.creator?.username}</span><time>{new Date(version.created_at).toLocaleString()}</time></button>)}</div>}</div>}{selectedVersion && <PageCompareModal version={selectedVersion} currentPage={page} restoring={restore.isPending} restoreError={restore.error} canRestore={!editingBy || editing} onRestore={() => { if (window.confirm(`Восстановить страницу из snapshot ${selectedVersion.version_number}? Текущее состояние сохранится отдельной версией.`)) restore.mutate(selectedVersion.id); }} onClose={() => navigate(`/books/${bookId}/pages/${pageId}`)}/>}</aside>;
}

function PageCompareModal({ version, currentPage, restoring, restoreError, canRestore, onRestore, onClose }) {
    const oldText = JSON.stringify(version.snapshot, null, 2); const newText = JSON.stringify(currentPageSnapshot(currentPage), null, 2); const rows = lineDiff(oldText, newText);
    return <div className="book-compare-backdrop" onMouseDown={onClose}><section className="book-compare-modal" onMouseDown={(event) => event.stopPropagation()}><header><div><small>BOOKER snapshot {version.version_number}</small><h2>Сравнение с текущей страницей</h2></div><div className="book-compare-actions"><button className="restore" disabled={!canRestore || restoring} title={canRestore ? 'Текущее состояние сначала сохранится новой версией' : 'Страница редактируется другим пользователем'} onClick={onRestore}>{restoring ? 'Восстанавливаю…' : 'Восстановить эту версию'}</button><button onClick={onClose}>Закрыть</button></div></header><div className="book-compare-meta"><span className="removed">− удалено</span><span className="added">+ добавлено</span>{restoreError && <span className="book-compare-error">{restoreError.message}</span>}<time>{new Date(version.created_at).toLocaleString()}</time></div><div className="book-diff">{rows.map((row, index) => <div key={index} className={row.type}><i>{row.oldLine ?? ''}</i><i>{row.newLine ?? ''}</i><b>{row.type === 'added' ? '+' : row.type === 'removed' ? '−' : ' '}</b><code>{row.text || ' '}</code></div>)}</div></section></div>;
}

function SortableStructureItem({ group, index, bookId, pageId, editing }) {
    const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id: group.id, disabled: !editing });
    return <div ref={setNodeRef} className="booker-structure-row" style={{ transform: CSS.Transform.toString(transform), transition, opacity: isDragging ? .45 : 1 }}>{editing && <button title="Перетащить блок" {...attributes} {...listeners}><IconGripVertical size={13}/></button>}<Link to={`/books/${bookId}/pages/${pageId}/blocks/${group.id}`}><span>{index + 1}</span>{BLOCK_TYPES.find(([type]) => type === group.type)?.[1] ?? group.type}</Link></div>;
}

function CreateBookerEntity({ form, setForm, scopeId, bookId, spaces, scopes, pages, onCreated }) {
    const [title, setTitle] = useState(''); const [targetScopeId, setTargetScopeId] = useState(scopeId); const [spaceId, setSpaceId] = useState(form.space_id ?? ''); const [parentId, setParentId] = useState('');
    const mutation = useMutation({ mutationFn: () => form.type === 'space' ? bookApi.createSpace(scopeId, { title }) : form.type === 'book' ? bookApi.createBook(targetScopeId, { title, space_id: targetScopeId === scopeId ? spaceId || null : null }) : bookApi.createPage(scopeId, bookId, { title, parent_id: parentId || null }), onSuccess: (entity) => onCreated(entity, targetScopeId) });
    return <div className="booker-modal-backdrop" onMouseDown={() => setForm(null)}><form className="booker-modal" onMouseDown={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}><h2>{form.type === 'space' ? 'Новый раздел Booker' : form.type === 'book' ? 'Новая книга' : 'Новая страница'}</h2><label>Название<input autoFocus required value={title} onChange={(event) => setTitle(event.target.value)}/></label>{form.type === 'book' && <><label>Скоуп<select value={targetScopeId} onChange={(event) => { setTargetScopeId(event.target.value); setSpaceId(''); }}>{scopes.map((scope) => <option key={scope.id} value={scope.id}>{scope.name}</option>)}</select></label><label>Раздел Booker<select disabled={targetScopeId !== scopeId} value={spaceId} onChange={(event) => setSpaceId(event.target.value)}><option value="">Без раздела</option>{spaces.map((space) => <option key={space.id} value={space.id}>{space.title}</option>)}</select>{targetScopeId !== scopeId && <small>Раздел можно выбрать после перехода в этот скоуп.</small>}</label></>}{form.type === 'page' && <label>Родительская страница<select value={parentId} onChange={(event) => setParentId(event.target.value)}><option value="">Корень книги</option>{treePages(pages).map((item) => <option key={item.id} value={item.id}>{'— '.repeat(item.depth)}{item.title}</option>)}</select></label>}{mutation.error && <p className="booker-error">{mutation.error.message}</p>}<footer><button type="button" onClick={() => setForm(null)}>Отмена</button><button className="booker-primary">Создать</button></footer></form></div>;
}

function BookerWelcome() { return <div className="booker-empty"><IconBook2 size={34}/><h2>Выберите книгу</h2><p>Слева живут книги, внутри — дерево страниц.</p></div>; }
function bookDraft(book) { return { title: book.title ?? '', scope_id: book.scope_id ?? '', space_id: book.space_id ?? '', project_id: book.project_id ?? '', description: book.description ?? '', visibility: book.visibility ?? 'private', structure_mode: book.structure_mode ?? 'tree', version_depth: book.version_depth ?? 25, cover_color: book.cover_color ?? '', cover_svg_url: book.cover_svg_url ?? '', cover_svg_text: book.cover_svg_text ?? '' }; }
function svgTextToDataUrl(svgText) { return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svgText)}`; }
function defaultPayload(type) { if (type === 'svg') return { source: 'url', url: '', svg_text: '', file_name: '', caption: '', max_width: '', max_height: '' }; if (type === 'code') return { caption: '', language: 'javascript', code: '' }; if (type === 'callout') return { tone: 'info', title: 'Заметка', text: '' }; if (type === 'divider') return { label: '' }; if (type === 'embed') return { title: '', url: '', description: '' }; if (type === 'table') return { caption: '', min_width: '720px', columns: ['Колонка 1', 'Колонка 2'], rows: [['', '']] }; if (type === 'checklist') return { items: [{ text: '', checked: false }] }; return {}; }
function currentPageSnapshot(page) { return { format: 'booker-page', format_version: 1, page: pick(page, ['id', 'book_id', 'parent_id', 'title', 'slug', 'visibility', 'sort_order', 'meta']), blocks: (page?.groups ?? []).map((group) => ({ group: pick(group, ['id', 'type', 'role', 'visibility', 'is_hidden_by_default', 'sort_order', 'meta']), block: group.master_block ? pick(group.master_block, ['id', 'version_number', 'title', 'content', 'payload', 'search_text', 'status', 'published_at']) : null })) }; }
function pick(source, keys) { return Object.fromEntries(keys.map((key) => [key, source?.[key] ?? null])); }
function lineDiff(before, after) { const left = before.split('\n').slice(0, 1200); const right = after.split('\n').slice(0, 1200); const matrix = Array.from({ length: left.length + 1 }, () => new Uint16Array(right.length + 1)); for (let i = left.length - 1; i >= 0; i--) for (let j = right.length - 1; j >= 0; j--) matrix[i][j] = left[i] === right[j] ? matrix[i + 1][j + 1] + 1 : Math.max(matrix[i + 1][j], matrix[i][j + 1]); const rows = []; let i = 0; let j = 0; let oldLine = 1; let newLine = 1; while (i < left.length || j < right.length) { if (i < left.length && j < right.length && left[i] === right[j]) { rows.push({ type: 'same', text: left[i], oldLine: oldLine++, newLine: newLine++ }); i++; j++; } else if (j < right.length && (i === left.length || matrix[i][j + 1] >= matrix[i + 1][j])) { rows.push({ type: 'added', text: right[j++], newLine: newLine++ }); } else { rows.push({ type: 'removed', text: left[i++], oldLine: oldLine++ }); } } return rows; }
function treePages(pages) { const byParent = new Map(); pages.forEach((page) => { const key = page.parent_id ?? 'root'; byParent.set(key, [...(byParent.get(key) ?? []), page]); }); const result = []; function walk(parent, depth) { (byParent.get(parent) ?? []).forEach((page) => { result.push({ ...page, depth }); walk(page.id, depth + 1); }); } walk('root', 0); return result; }
