import { lazy, Suspense, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { IconCalendarEvent, IconClock, IconMapPin, IconPlus, IconSearch, IconSettings, IconX } from '@tabler/icons-react';
import { useWorkspace } from '../app/workspace';
import { eventApi } from '../entities/event/api';
import './EventorPage.css';

const MarkdownEditor = lazy(() => import('../shared/ui/CompactMarkdownEditor'));

export function EventorPage() {
  const { activeScope } = useWorkspace();
  const queryClient = useQueryClient();
  const [search, setSearch] = useState('');
  const [createOpen, setCreateOpen] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [selectedId, setSelectedId] = useState(null);
  const eventsKey = ['events', activeScope?.id];
  const { data: events = [], isLoading, error } = useQuery({ queryKey: eventsKey, queryFn: () => eventApi.list(activeScope.id), enabled: Boolean(activeScope) });
  const { data: types = [] } = useQuery({ queryKey: ['event-types', activeScope?.id], queryFn: () => eventApi.types(activeScope.id), enabled: Boolean(activeScope) });
  const { data: sections = [] } = useQuery({ queryKey: ['event-sections', activeScope?.id], queryFn: () => eventApi.sections(activeScope.id), enabled: Boolean(activeScope) });
  const filtered = events.filter((event) => `${event.title} ${event.location ?? ''}`.toLowerCase().includes(search.toLowerCase()));
  const refresh = () => queryClient.invalidateQueries({ queryKey: eventsKey });
  return <main className="eventor-page"><header className="eventor-toolbar"><div><IconCalendarEvent size={20}/><h1>Eventor</h1><small>{events.length} событий</small></div><label><IconSearch size={17}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Найти событие…"/></label><button className="event-settings-button" onClick={() => setSettingsOpen(true)}><IconSettings size={17}/></button><button className="new-event" onClick={() => setCreateOpen(true)}><IconPlus size={17}/>Новое событие</button></header>{isLoading && <div className="eventor-state">Загружаю события…</div>}{error && <div className="eventor-state eventor-error">{error.message}</div>}<section className="event-list">{filtered.map((event) => <button key={event.id} onClick={() => setSelectedId(event.id)}><time><strong>{eventDate(event)}</strong><small>{eventTime(event)}</small></time><i style={{ background: event.type?.color ?? '#3975c6' }}/><div><header><strong>{event.title}</strong><span>{event.type?.name ?? 'Без типа'}</span></header><footer>{event.section?.name && <span>{event.section.name}</span>}{event.location && <span><IconMapPin size={13}/>{event.location}</span>}<span className={`event-status event-status--${event.status}`}>{event.status}</span></footer></div></button>)}{!isLoading && filtered.length === 0 && <div className="eventor-state">Событий пока нет.</div>}</section>{createOpen && <EventCreate scopeId={activeScope.id} types={types} sections={sections} onClose={() => setCreateOpen(false)} onCreated={(event) => { refresh(); setCreateOpen(false); setSelectedId(event.id); }}/>} {settingsOpen && <EventSettings scopeId={activeScope.id} types={types} sections={sections} onClose={() => setSettingsOpen(false)} onChanged={() => { queryClient.invalidateQueries({ queryKey: ['event-types', activeScope.id] }); queryClient.invalidateQueries({ queryKey: ['event-sections', activeScope.id] }); }}/>} {selectedId && <><div className="event-backdrop" onClick={() => setSelectedId(null)}/><EventEditor scopeId={activeScope.id} eventId={selectedId} types={types} sections={sections} onClose={() => setSelectedId(null)} onChanged={refresh}/></>}</main>;
}

function EventCreate({ scopeId, types, sections, onClose, onCreated }) {
  const [form, setForm] = useState({ title: '', type_id: '', section_id: '', starts_at: '', ends_at: '', location: '', status: 'draft', is_all_day: false });
  const create = useMutation({ mutationFn: () => eventApi.create(scopeId, { ...form, type_id: form.type_id || null, section_id: form.section_id || null, starts_at: form.starts_at || null, ends_at: form.ends_at || null, location: form.location || null }), onSuccess: onCreated });
  const set = (key) => (event) => setForm((value) => ({ ...value, [key]: event.target.type === 'checkbox' ? event.target.checked : event.target.value }));
  return <div className="event-modal-backdrop" onMouseDown={onClose}><form className="event-modal" onMouseDown={(event) => event.stopPropagation()} onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><header><strong>Новое событие</strong><button type="button" onClick={onClose}><IconX size={18}/></button></header><label>Название<input autoFocus required value={form.title} onChange={set('title')}/></label><div className="event-form-row"><label>Тип<select value={form.type_id} onChange={set('type_id')}><option value="">Без типа</option>{types.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></label><label>Секция<select value={form.section_id} onChange={set('section_id')}><option value="">Без секции</option>{sections.map((section) => <option key={section.id} value={section.id}>{section.name}</option>)}</select></label></div><div className="event-form-row"><label>Начало<input type="datetime-local" value={form.starts_at} onChange={set('starts_at')}/></label><label>Окончание<input type="datetime-local" value={form.ends_at} onChange={set('ends_at')}/></label></div><label>Место<input value={form.location} onChange={set('location')}/></label><label className="event-checkbox"><input type="checkbox" checked={form.is_all_day} onChange={set('is_all_day')}/>Весь день</label>{create.error && <p className="eventor-error">{create.error.message}</p>}<footer><button type="button" onClick={onClose}>Отмена</button><button className="event-primary">Создать</button></footer></form></div>;
}

function EventEditor({ scopeId, eventId, types, sections, onClose, onChanged }) {
  const queryClient = useQueryClient(); const key = ['event', scopeId, eventId];
  const { data: event, isLoading, error } = useQuery({ queryKey: key, queryFn: () => eventApi.get(scopeId, eventId) });
  const save = useMutation({ mutationFn: (payload) => eventApi.update(scopeId, eventId, payload), onSuccess: (updated) => { queryClient.setQueryData(key, updated); onChanged(); } });
  if (isLoading) return <aside className="event-editor">Загружаю…</aside>; if (error) return <aside className="event-editor eventor-error">{error.message}</aside>;
  return <aside className="event-editor"><header><span><IconCalendarEvent size={18}/>Событие</span><button onClick={onClose}><IconX size={19}/></button></header><input className="event-title" value={event.title} onChange={(input) => queryClient.setQueryData(key, { ...event, title: input.target.value })} onBlur={(input) => save.mutate({ title: input.target.value })}/><div className="event-properties"><label>Статус<select value={event.status} onChange={(input) => save.mutate({ status: input.target.value })}><option value="draft">Черновик</option><option value="published">Опубликовано</option><option value="archived">Архив</option></select></label><label>Тип<select value={event.type_id ?? ''} onChange={(input) => save.mutate({ type_id: input.target.value || null })}><option value="">Без типа</option>{types.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select></label><label>Секция<select value={event.section_id ?? ''} onChange={(input) => save.mutate({ section_id: input.target.value || null })}><option value="">Без секции</option>{sections.map((section) => <option key={section.id} value={section.id}>{section.name}</option>)}</select></label></div><div className="event-dates"><label><IconClock size={15}/>Начало<input type="datetime-local" defaultValue={localDateTime(event.starts_at)} onBlur={(input) => save.mutate({ starts_at: input.target.value || null })}/></label><label><IconClock size={15}/>Окончание<input type="datetime-local" defaultValue={localDateTime(event.ends_at)} onBlur={(input) => save.mutate({ ends_at: input.target.value || null })}/></label><label><IconMapPin size={15}/>Место<input defaultValue={event.location ?? ''} onBlur={(input) => save.mutate({ location: input.target.value || null })}/></label></div><Suspense fallback={<div className="eventor-state">Загружаю Markdown…</div>}><MarkdownEditor variant="full" value={event.content} placeholder="Описание и материалы события…" onSave={(content) => save.mutate({ content })}/></Suspense>{save.error && <p className="eventor-error">{save.error.message}</p>}</aside>;
}

function EventSettings({ scopeId, types, sections, onClose, onChanged }) {
  const [typeName, setTypeName] = useState(''); const [sectionName, setSectionName] = useState('');
  const createType = useMutation({ mutationFn: () => eventApi.createType(scopeId, { name: typeName, color: '#3975c6' }), onSuccess: () => { setTypeName(''); onChanged(); } });
  const createSection = useMutation({ mutationFn: () => eventApi.createSection(scopeId, { name: sectionName, visibility: 'private' }), onSuccess: () => { setSectionName(''); onChanged(); } });
  return <div className="event-modal-backdrop" onMouseDown={onClose}><section className="event-modal event-settings" onMouseDown={(event) => event.stopPropagation()}><header><strong>Справочники Eventor</strong><button onClick={onClose}><IconX size={18}/></button></header><div><h3>Типы</h3>{types.map((type) => <p key={type.id}><i style={{background:type.color ?? '#3975c6'}}/>{type.name}</p>)}<form onSubmit={(event) => { event.preventDefault(); if(typeName.trim()) createType.mutate(); }}><input value={typeName} onChange={(event) => setTypeName(event.target.value)} placeholder="Новый тип"/><button>Добавить</button></form></div><div><h3>Секции</h3>{sections.map((section) => <p key={section.id}>{section.name}</p>)}<form onSubmit={(event) => { event.preventDefault(); if(sectionName.trim()) createSection.mutate(); }}><input value={sectionName} onChange={(event) => setSectionName(event.target.value)} placeholder="Новая секция"/><button>Добавить</button></form></div></section></div>;
}

function eventDate(event) { const value = event.starts_at ?? event.occurred_at; return value ? new Date(value).toLocaleDateString([], { day:'2-digit', month:'short' }) : 'Без даты'; }
function eventTime(event) { const value = event.starts_at ?? event.occurred_at; return value && !event.is_all_day ? new Date(value).toLocaleTimeString([], { hour:'2-digit', minute:'2-digit' }) : event.is_all_day ? 'Весь день' : ''; }
function localDateTime(value) { if (!value) return ''; const date = new Date(value); const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0,16); }
