import { useState, type FormEvent } from 'react'
import { IconLock, IconRocket, IconSparkles, IconUser } from '@tabler/icons-react'
import { Navigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useAuth } from '../auth'
import { Brand } from '../shared/ui/Brand'
import { LanguageMenu } from '../shared/ui/LanguageMenu'

export function LoginPage() {
  const { t } = useTranslation(); const { user, login } = useAuth(); const [error, setError] = useState(''); const [submitting, setSubmitting] = useState(false)
  if (user) return <Navigate to="/" replace/>
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); setError(''); setSubmitting(true); try { await login(String(data.get('identity')), String(data.get('password'))) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Login failed.') } finally { setSubmitting(false) } }
  return <main className="public-page"><section className="login-pane"><header className="public-header"><Brand/><LanguageMenu/></header><div className="login-card"><p className="eyebrow">PRIVATE WORKSPACE</p><h1>{t('welcome')}</h1><p className="lead">{t('loginLead')}</p><form onSubmit={submit}><label>{t('identity')}<span className="field"><IconUser size={18}/><input name="identity" type="text" placeholder="name@company.com" autoComplete="username" required/></span></label><label><span className="label-row"><span>{t('password')}</span><a href="#forgot">{t('forgot')}</a></span><span className="field"><IconLock size={18}/><input name="password" type="password" placeholder="••••••••" autoComplete="current-password" required/></span></label><button className="primary-button" type="submit" disabled={submitting}>{t('login')} <span>→</span></button>{error && <p className="login-error" role="alert">{error}</p>}</form><div className="system-status"><span/>{t('status')}</div></div><footer className="public-footer"><nav><a href="#features">{t('features')}</a><a href="#changelog">{t('changelog')}</a><a href="#docs">{t('docs')}</a><a href="https://github.com" target="_blank">GitHub</a><a href="#self-hosting">{t('selfHosting')}</a></nav><small>© 2026 Zuratax · v2.1</small></footer></section><section className="release-pane"><img src="/mascot-release.png" alt="" className="release-pane__image"/><article className="release-card"><div className="release-card__meta"><span>{t('version')}</span><i/></div><h2>{t('releaseTitle')}</h2><p>{t('releaseText')}</p><div className="release-features"><span><IconSparkles size={18}/> Smart sorting</span><span><IconRocket size={18}/> Faster workflows</span></div><div className="release-actions"><a href="#changelog">{t('whatsNew')} ↗</a><a href="https://github.com" target="_blank">{t('deploy')} ↗</a></div></article></section></main>
}
