import { lazy, Suspense, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { IconBrain, IconHistory, IconPlus, IconSearch, IconStar, IconX } from '@tabler/icons-react';
import { useWorkspace } from '../app/workspace';
import { loreApi } from '../entities/lore/api';
import { projectApi } from '../entities/project/api';
import MarkdownRenderer from '../shared/ui/MarkdownRenderer';
import './LorePage.css';
import './LoreMarkdown.css';

const MarkdownEditor = lazy(() => import('../shared/ui/CompactMarkdownEditor'));

const types = { decision:'Решение', mechanic:'Механика', convention:'Соглашение', constraint:'Ограничение', hypothesis:'Гипотеза', question:'Вопрос', context:'Контекст', incident:'Инцидент', handoff:'Передача' };
const importance = { foundational:'Основополагающее', architectural:'Архитектурное', mechanic:'Механика', detail:'Деталь' };
const criticality = { informational:'Информация', warning:'Нежелательно нарушать', compatibility:'Сломает совместимость', critical:'Критично' };
const empty = { code:'', title:'', content:'', reason:'', project_id:'', area_id:'', type:'decision', importance:'mechanic', criticality:'informational', visibility:'scope', status:'active', effective_from:'', tags:'' };

export function LorePage() {
  const { activeScope } = useWorkspace();
  const queryClient = useQueryClient();
  const [filters, setFilters] = useState({ q:'', type:'', importance:'', starred:'' });
  const [selected, setSelected] = useState(null);
  const [creating, setCreating] = useState(false);
  const key = ['lore', activeScope?.id, filters];
  const { data: entries = [], isLoading, error } = useQuery({ queryKey:key, queryFn:()=>loreApi.list(activeScope.id, filters), enabled:Boolean(activeScope) });
  const star = useMutation({ mutationFn:(entry)=>loreApi.star(activeScope.id, entry.id, !entry.is_starred), onSuccess:()=>queryClient.invalidateQueries({queryKey:['lore', activeScope.id]}) });
  const groups = useMemo(() => ({ starred:entries.filter((item)=>item.is_starred), rest:entries.filter((item)=>!item.is_starred) }), [entries]);
  return <main className="lore-page">
    <header className="lore-toolbar"><div><IconBrain size={21}/><span><small>Память проекта</small><h1>Lore</h1></span></div><button onClick={()=>setCreating(true)}><IconPlus size={16}/>Новая запись</button></header>
    <section className="lore-filters"><label><IconSearch size={15}/><input value={filters.q} onChange={(e)=>setFilters({...filters,q:e.target.value})} placeholder="Решение, код или текст…"/></label><select value={filters.type} onChange={(e)=>setFilters({...filters,type:e.target.value})}><option value="">Все типы</option>{Object.entries(types).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={filters.importance} onChange={(e)=>setFilters({...filters,importance:e.target.value})}><option value="">Все уровни</option>{Object.entries(importance).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><button className={filters.starred?'active':''} onClick={()=>setFilters({...filters,starred:filters.starred?'':'1'})}><IconStar size={14}/>Мои звёзды</button>{Object.values(filters).some(Boolean)&&<button onClick={()=>setFilters({q:'',type:'',importance:'',starred:''})}><IconX size={14}/>Сбросить</button>}</section>
    {isLoading&&<div className="lore-state">Загружаю память…</div>}{error&&<div className="lore-state lore-error">{error.message}</div>}
    {!isLoading&&!error&&<><LoreList title="Перед носом" entries={groups.starred} onOpen={setSelected} onStar={star.mutate}/><LoreList title="Все актуальные записи" entries={groups.rest} onOpen={setSelected} onStar={star.mutate}/></>}
    {creating&&<LoreForm scopeId={activeScope.id} onClose={()=>setCreating(false)} onDone={()=>{setCreating(false);queryClient.invalidateQueries({queryKey:['lore',activeScope.id]});}}/>}
    {selected&&<LoreDrawer scopeId={activeScope.id} id={selected} onClose={()=>setSelected(null)} onChanged={()=>queryClient.invalidateQueries({queryKey:['lore',activeScope.id]})}/>} 
  </main>;
}

function LoreList({title,entries,onOpen,onStar}) { if(!entries.length)return null; return <section className="lore-list"><header><h2>{title}</h2><small>{entries.length}</small></header><div className="lore-table">{entries.map((entry)=>{const rev=entry.current_revision;return <article key={entry.id} onClick={()=>onOpen(entry.id)}><button className={entry.is_starred?'starred':''} onClick={(e)=>{e.stopPropagation();onStar(entry);}}><IconStar size={15} fill={entry.is_starred?'currentColor':'none'}/></button><span className="lore-code">{entry.code}</span><div><strong>{rev?.title||'Нет актуальной версии'}</strong><p>{rev?.content}</p><footer>{entry.area&&<span>{entry.area.name}</span>}{entry.tags.map((tag)=><i key={tag.id}>#{tag.name}</i>)}</footer></div><span className={`lore-level level-${entry.importance}`}>{importance[entry.importance]}</span><span className={`lore-critical critical-${entry.criticality}`}>{criticality[entry.criticality]}</span><time>v{rev?.version||'—'} · {rev?.effective_from?new Date(rev.effective_from).toLocaleDateString('ru-RU'):'—'}</time></article>})}</div></section> }

function LoreForm({scopeId,onClose,onDone}) {
  const [form,setForm]=useState(empty); const {data:projects=[]}=useQuery({queryKey:['projects',scopeId],queryFn:()=>projectApi.list(scopeId)}); const {data:areas=[]}=useQuery({queryKey:['lore-areas',scopeId],queryFn:()=>loreApi.areas(scopeId)});
  const create=useMutation({mutationFn:()=>loreApi.create(scopeId,{...form,project_id:form.project_id||null,area_id:form.area_id||null,effective_from:form.effective_from||new Date().toISOString(),tags:form.tags.split(',').map((x)=>x.trim()).filter(Boolean)}),onSuccess:onDone}); const set=(key)=>(e)=>setForm({...form,[key]:e.target.value});
  return <div className="lore-backdrop" onMouseDown={onClose}><form className="lore-modal" onMouseDown={(e)=>e.stopPropagation()} onSubmit={(e)=>{e.preventDefault();create.mutate();}}><header><div><small>Новая цепочка</small><h2>Зафиксировать знание</h2></div><button type="button" onClick={onClose}><IconX/></button></header><div className="lore-form-grid"><label>Код<input required value={form.code} onChange={set('code')} placeholder="AUTH-FRONT"/></label><label>Проект<select value={form.project_id} onChange={set('project_id')}><option value="">Весь скоуп</option>{projects.map((p)=><option key={p.id} value={p.id}>{p.key} · {p.title}</option>)}</select></label><label>Тип<select value={form.type} onChange={set('type')}>{Object.entries(types).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Область<select value={form.area_id} onChange={set('area_id')}><option value="">Без области</option>{areas.map((a)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Значимость<select value={form.importance} onChange={set('importance')}>{Object.entries(importance).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Критичность<select value={form.criticality} onChange={set('criticality')}>{Object.entries(criticality).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><label>Заголовок<input autoFocus required value={form.title} onChange={set('title')}/></label><div className="lore-md-field"><strong>Актуальное решение · Markdown</strong><Suspense fallback={<div className="lore-state">Загружаю редактор…</div>}><MarkdownEditor value={form.content} onChange={(content)=>setForm((value)=>({...value,content}))} toolbarInitiallyOpen hideToolbarTrigger variant="full"/></Suspense></div><div className="lore-md-field lore-md-field--reason"><strong>Причина решения · Markdown</strong><Suspense fallback={null}><MarkdownEditor value={form.reason} onChange={(reason)=>setForm((value)=>({...value,reason}))} toolbarInitiallyOpen hideToolbarTrigger/></Suspense></div><label>Теги через запятую<input value={form.tags} onChange={set('tags')} placeholder="безопасность, jwt, агенты"/></label>{create.error&&<p className="lore-error">{create.error.message}</p>}<footer><button type="button" onClick={onClose}>Отмена</button><button className="primary" disabled={create.isPending||!form.content.trim()}>Зафиксировать v1</button></footer></form></div>
}

function LoreDrawer({scopeId,id,onClose,onChanged}) {
  const key=['lore-entry',scopeId,id]; const queryClient=useQueryClient(); const {data:entry,isLoading,error}=useQuery({queryKey:key,queryFn:()=>loreApi.get(scopeId,id)}); const [draft,setDraft]=useState(null);
  const revise=useMutation({mutationFn:()=>loreApi.revise(scopeId,id,{...draft,effective_from:draft.effective_from||new Date().toISOString(),status:'active'}),onSuccess:(data)=>{queryClient.setQueryData(key,data);setDraft(null);onChanged();}});
  if(isLoading)return <aside className="lore-drawer">Загружаю…</aside>; if(error)return <aside className="lore-drawer lore-error">{error.message}</aside>; const rev=entry.current_revision;
  return <><div className="lore-drawer-backdrop" onClick={onClose}/><aside className="lore-drawer"><header><div><small>{entry.code} · {importance[entry.importance]}</small><h2>{rev?.title}</h2></div><button onClick={onClose}><IconX/></button></header><div className="lore-current"><span>Актуально с {new Date(rev.effective_from).toLocaleString('ru-RU')}</span><MarkdownRenderer>{rev.content}</MarkdownRenderer>{rev.reason&&<blockquote><strong>Почему</strong><MarkdownRenderer>{rev.reason}</MarkdownRenderer></blockquote>}</div><section className="lore-history"><h3><IconHistory size={16}/>История решения</h3>{entry.revisions.map((item)=><article key={item.id}><strong>v{item.version} · {item.title}</strong><time>{new Date(item.effective_from).toLocaleDateString('ru-RU')}{item.effective_until?` — ${new Date(item.effective_until).toLocaleDateString('ru-RU')}`:' — сейчас'}</time><MarkdownRenderer>{item.content}</MarkdownRenderer>{item.reason&&<small><MarkdownRenderer>{item.reason}</MarkdownRenderer></small>}</article>)}</section>{!draft?<button className="lore-new-version" onClick={()=>setDraft({title:rev.title,content:rev.content,reason:'',effective_from:''})}><IconPlus size={15}/>Новая смысловая версия</button>:<form className="lore-revise" onSubmit={(e)=>{e.preventDefault();revise.mutate();}}><h3>Следующая версия</h3><input required value={draft.title} onChange={(e)=>setDraft({...draft,title:e.target.value})}/><div className="lore-md-field"><strong>Решение · Markdown</strong><Suspense fallback={null}><MarkdownEditor value={draft.content} onChange={(content)=>setDraft((value)=>({...value,content}))} toolbarInitiallyOpen hideToolbarTrigger variant="full"/></Suspense></div><div className="lore-md-field lore-md-field--reason"><strong>Причина · Markdown</strong><Suspense fallback={null}><MarkdownEditor value={draft.reason} onChange={(reason)=>setDraft((value)=>({...value,reason}))} toolbarInitiallyOpen hideToolbarTrigger/></Suspense></div><label>Действует с<input type="datetime-local" value={draft.effective_from} onChange={(e)=>setDraft({...draft,effective_from:e.target.value})}/></label>{revise.error&&<p className="lore-error">{revise.error.message}</p>}<footer><button type="button" onClick={()=>setDraft(null)}>Отмена</button><button className="primary" disabled={!draft.content.trim()}>Опубликовать v{entry.versions_count+1}</button></footer></form>}</aside></>;
}
